In [1]:
# Needed libraries imported

import numpy as np
import random

In [9]:
#34 Getting the dates corresponding to the month of July 2016

print("July, 2016")
print(np.arange('2016-07', '2016-08', dtype ='datetime64[D]'))

July, 2016
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [28]:
#42. Considering two random array A and B, and checking if they are equal
array_A = np.random.uniform(size=(3, 3))
array_B = np.random.uniform(size=(3, 3))

print("A is ", array_A)
print("B is ", array_B)
print("Is A and B equal: ", array_A is array_B)

A is  [[0.94888594 0.30923896 0.93427144]
 [0.30142622 0.67599573 0.66456931]
 [0.92666859 0.42136618 0.2419281 ]]
B is  [[0.36401774 0.88887515 0.09022279]
 [0.15485347 0.19786308 0.63394752]
 [0.74816484 0.31594488 0.73429798]]
Is A and B equal:  False
