In [26]:
#Needed libraries imported

import numpy as np
import random

In [27]:
#13 A 10x10 array with random values and finding the minimum and maximum values

In [46]:
ten_by_ten = np.random.normal(size = (10, 10))
print(ten_by_ten)
minimum = ten_by_ten.min()
maximum = ten_by_ten.max()
print("Minimum value is ", minimum,  "Maximum value is ", maximum)

[[-1.82527743e+00  1.81153046e+00 -1.05603708e+00  1.02138619e+00
   1.29975550e+00  3.86431912e-01 -6.86726441e-02 -1.20523682e+00
   1.85037209e-01  9.38478082e-01]
 [ 3.52209999e-01  4.27229345e-01 -8.93568656e-01  7.78826001e-01
   6.06216755e-01  1.17039245e+00  6.31258086e-01  4.93401053e-01
  -7.24223127e-02  3.62859083e-01]
 [ 2.02406424e+00  1.47854125e-01 -5.84024906e-01  2.28308646e-01
  -6.77891898e-02  1.68332440e+00 -3.08104679e-01  5.83511186e-01
   7.44530833e-02 -1.46776046e-01]
 [-1.63489977e-01 -9.79250304e-01  4.62718794e-01  3.23150057e-01
  -9.60294448e-01  1.61713030e+00  4.51374292e-01  7.40377193e-01
   7.99364987e-01 -1.32744134e+00]
 [ 2.89388516e-01  9.64137308e-01 -4.84029345e-02 -8.32161837e-01
   1.40528919e+00  5.63834742e-01 -1.35849846e+00 -7.74248414e-03
   1.98896117e+00 -3.18502925e-01]
 [-9.72868240e-01  3.61031330e-01  2.49359861e-01 -1.30084258e+00
  -2.93257954e-01 -2.29417842e+00 -7.69633410e-01  2.33051630e-01
   8.35573370e-01  5.43734584e-02

In [31]:
#15 A 2D Array

In [24]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
