In [26]:
#Needed libraries imported

import numpy as np

In [27]:
#13 A 10x10 array with random values and finding the minimum and maximum values

In [28]:
np.random.normal(size=(10, 10))

array([[-3.45545135e-01,  4.93544683e-01, -8.58198283e-01,
        -6.48479442e-01,  4.85921502e-01,  2.62248859e-01,
        -1.61742526e+00, -7.89628520e-01,  2.46937891e-01,
         2.63212548e+00],
       [-1.13453917e+00,  4.81232393e-01,  2.62141904e+00,
         3.84494833e-01, -5.56003121e-01,  3.39825846e-01,
         3.76043106e-01,  3.42323275e-01, -1.62745113e+00,
         5.59819400e-01],
       [ 2.59445472e-01, -1.39436264e+00,  1.52554041e+00,
        -8.05022270e-01, -1.23341720e-01,  6.76400694e-01,
        -6.40398321e-01,  6.15542528e-01,  8.73896104e-01,
         1.11570684e+00],
       [-1.54431650e+00,  1.26532101e+00, -1.16342705e+00,
         1.07564558e+00, -1.59586581e+00,  7.10692501e-01,
         1.32085019e-01, -3.43070614e-01, -3.91178317e-02,
        -5.97210158e-01],
       [ 7.75363670e-01, -8.38995503e-01, -6.31538038e-02,
         2.72720373e-01,  1.49600101e+00, -3.73281984e-01,
         5.69885273e-01,  5.63966689e-02,  4.09844225e-01,
        -1.

In [29]:
np.random.normal(size=(10, 10)).min()

-2.144217151909039

In [30]:
np.random.normal(size=(10, 10)).max()

2.5615745923647886

In [31]:
#15 A 2D Array

In [24]:
arr = np.ones((5,5))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
