In [1]:
# Import all needed libraries

import numpy as np
import random

In [4]:
#72. Swapping two rows of an array using Transpose

# First create the array

the_array = np.arange(10)
print(the_array)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
# Then reshape it

the_array = the_array.reshape(2,5)
the_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
# Then, Transpose to swap the two rows...

the_array.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [14]:
#75. Computing averages using a sliding window over an array

def moving_average(a, n) :
    test = np.cumsum(a, dtype = float)
    test[n:] = test[n:] - test[:-n]
    return test[n - 1:] / n
moving_average(np.arange(60),5)

array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
       28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40.,
       41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53.,
       54., 55., 56., 57.])