In [1]:
import numpy as np

In [2]:
a = [1, 2]
b = [2, 3]

In [3]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([2, 3, 3, 0, 0])

In [4]:
a + b

array([3, 5, 6, 4, 5])

In [5]:
a

array([1, 2, 3, 4, 5])

## Using the norm function 

In [6]:
np.linalg.norm(a)

7.416198487095663

# # ## Using the manual (sqrt) function 

In [7]:
np.sqrt(1*1 + 2*2 + 3*3 + 4*4 + 5*5)

7.416198487095663

In [10]:
a = [1,2,3]

np.cumsum(a)

array([1, 3, 6])